In [31]:
import numpy as np
from numpy import eye, array, arange, zeros, ones, linspace
from numpy.random import rand, randint, randn

In [3]:
arr = np.array([1,2,3,4])

In [4]:
arr

array([1, 2, 3, 4])

In [8]:
my_list = [1,2,3]

In [9]:
arr = np.array(my_list)
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
rand(3)

array([0.34433985, 0.18575464, 0.01433644])

In [34]:
randn(6)

array([-0.23121976, -0.9784897 , -0.45392132, -1.2701887 , -0.41745964,
       -1.58914685])

In [36]:
randn(5,5)

array([[ 0.480668  ,  1.23721706, -1.64276779,  2.47531459,  0.1098282 ],
       [ 0.74798873, -0.64253696, -2.0935711 , -0.20267243, -1.10509112],
       [ 0.51506637,  0.25059117,  2.38726339, -0.33167313,  0.21077234],
       [-1.30902377, -1.40774678, -1.57973518,  0.38584241, -0.80394718],
       [-0.52957125,  0.18322386,  0.80879733,  1.9393393 , -2.06871284]])

In [37]:
randint(1,100,500)

array([25, 49, 38, 94, 49, 56, 15, 74, 78, 15, 42, 74, 81, 52, 76, 22, 39,
       38, 21, 34, 28, 99, 20, 62, 33, 11, 94, 17, 15, 52, 68,  6, 66, 89,
       26, 34, 40, 37, 74, 46, 49, 57, 56, 98, 94, 36, 57, 40, 18, 94, 34,
       80, 72, 48, 90, 21, 92, 81, 18, 71,  8, 33, 25, 39, 65, 68, 90, 60,
       79, 77, 21,  1, 26,  8, 87,  3, 54, 93, 30, 86, 13, 50, 13, 33, 72,
       41, 80, 84, 66, 22, 97, 42, 47, 61,  8, 93, 82, 64, 71, 77, 41, 81,
       20, 79, 97,  6, 29, 96, 96, 63, 26, 67, 37, 79, 80, 35, 14, 78, 86,
       11, 12, 73, 17, 93, 97, 35, 67, 32, 75, 38, 11, 21, 54,  9, 33, 28,
       69, 95, 44, 86, 96, 46, 34, 35, 95, 97,  1,  2, 53, 80, 28, 19,  8,
       44, 52,  9, 17, 28, 32, 78, 52, 71, 13, 75, 33, 50, 19, 19, 77, 16,
       41, 87, 13, 29, 75,  2, 40,  2, 27, 79, 89, 45, 97, 80, 89, 28, 89,
       52,  4, 58, 40, 76, 54, 21,  6, 72, 88, 20, 68, 73, 79,  6, 51, 28,
       51,  2, 49, 54,  9, 10, 89, 12, 63, 67, 20, 26, 39,  9, 48, 68, 11,
       67, 69, 56,  8, 24

In [38]:
arr = arange(25)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
ranarr = randint(0,50,10)

In [41]:
ranarr

array([21, 24, 26, 39,  3, 31, 43, 34, 33, 44])

In [42]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
ranarr

array([21, 24, 26, 39,  3, 31, 43, 34, 33, 44])

In [44]:
ranarr.max()

44

In [46]:
ranarr.min()

3

In [47]:
ranarr.argmin()

4

In [48]:
ranarr.argmin()

4

In [50]:
arr.shape

(25,)

In [51]:
arr.dtype

dtype('int32')