In [7]:
import numpy as np
from numpy import reshape, arange, eye, std, zeros, ones, linspace, reshape
from numpy.random import rand, randn

In [13]:
zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [42]:
ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [43]:
arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [44]:
arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [47]:
arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
rand(1)

array([0.33852913])

In [53]:
randn(25)

array([ 0.09855865, -0.74877697,  0.7020531 , -1.24353392, -0.05610165,
       -0.50501584, -0.77379722,  1.15704539,  1.36721375,  0.83859305,
       -1.64624344,  1.02779033, -0.65099665, -0.74125223,  0.85663103,
       -0.29208345,  0.18092797, -0.29545804, -0.22060827,  0.92265968,
        3.31604467, -0.20622046,  1.24757867,  1.72768786,  0.36904332])

In [29]:
linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [34]:
mat = arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [35]:
mat_copy = mat.copy()
mat_copy

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [36]:
mat_copy_slice = mat_copy[2:,1:]
mat_copy_slice

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [51]:
mat_copy_slice[1, -1]


20

In [10]:
# mat = arange(1,26).reshape(5,5)
mat.sum()

325

In [11]:
std(mat)

7.211102550927978

In [12]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])