In [27]:
import numpy as np
from numpy import arange, array

In [5]:
arr = arange(0,11)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [10]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [13]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = arange(0,11)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_arr = arr[0:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr_copy[:] = 100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
 arr_2d = array([[5,10,15],[20,25,30],[35,40,45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[1][2]

30

In [33]:
arr_2d[1,2]

30

In [34]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
arr = arange(1,11)

In [41]:
bool_arr = arr > 5

In [42]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [43]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [44]:
arr[arr<5]

array([1, 2, 3, 4])

In [45]:
arr = arange(50).reshape(5,10)

In [46]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
slice_arr = arr[:2, 5:]

In [48]:
slice_arr

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])